services:
  # 1. Database (MySQL)
  mysql:
    image: mysql:8.0
    container_name: task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. RabbitMQ (Messaging)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: task-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # App connection
      - "15672:15672" # Dashboard (http://localhost:15672)

  # 3. Kafka (Using Redpanda for simplicity/speed)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: task-kafka
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"

  # 4. Keycloak (Security)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: task-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --http-port=8081 # Run on 8081 to avoid conflict with Quarkus (8080)
    ports:
      - "8081:8081"

volumes:
  mysql_data: