services:
  # 1. Database (MySQL)
  mysql:
    image: mysql:8.0
    container_name: task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306" # Exposed to localhost:3306 so your local app can reach it
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: task-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # App connects here (localhost:5672)
      - "15672:15672" # Dashboard
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  # 3. Kafka (Redpanda)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: task-kafka
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      # Configures it so it works inside Docker AND on your localhost:9092
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: task-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --http-port=8081
    ports:
      - "8081:8081" # App connects here (localhost:8081)
    volumes:
      - keycloak_data:/opt/keycloak/data/
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8081;echo -e \"GET /health/ready HTTP/1.1\r\nhost: localhost:8081\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  keycloak_data: